import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Montserrat } from "next/font/google";
import { Comfortaa } from "next/font/google";
import "./globals.css";

import Image from "next/image";

const montserrat = Montserrat({
  subsets: ["latin"]
});

const comfortaa = Comfortaa({
  subsets: ["latin"]
});
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="header">
          <Image alt={"biba"} src={`/full_v4.png`}  className={ "header-logo " } width={120} height={40} />
        </div>
        {children}
      </body>
    </html>
  );
}
